//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFOInvasion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UFOInvasion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to begin.
        /// </summary>
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Loaded: {0}.
        /// </summary>
        internal static string gameLoaded {
            get {
                return ResourceManager.GetString("gameLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER.
        /// </summary>
        internal static string gameOver {
            get {
                return ResourceManager.GetString("gameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saved: .
        /// </summary>
        internal static string gameSaved {
            get {
                return ResourceManager.GetString("gameSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving.
        /// </summary>
        internal static string gameSaveFailed {
            get {
                return ResourceManager.GetString("gameSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Game: {1} // Score: {2}.
        /// </summary>
        internal static string highScore {
            get {
                return ResourceManager.GetString("highScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEADERBOARD.
        /// </summary>
        internal static string leaderTitle {
            get {
                return ResourceManager.GetString("leaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL: {0}.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVES: {0}    SCORE: {1}.
        /// </summary>
        internal static string livesScore {
            get {
                return ResourceManager.GetString("livesScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give your game a name.
        /// </summary>
        internal static string saveGame {
            get {
                return ResourceManager.GetString("saveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game.
        /// </summary>
        internal static string saveGameTitle {
            get {
                return ResourceManager.GetString("saveGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCORE: {0}.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WIN!.
        /// </summary>
        internal static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
    }
}
